name: mnist
model: DriftDiT-Tiny

use_feature_encoder: false
use_latent: false
use_spatial_features: false

precompute_drop_flip: true
fid_drop_flip: true

img_size: 28
in_channels: 1
patch_size: 4
num_register_tokens: 16

num_classes: 10
samples_per_class: 10
batch_n_pos: 8
batch_n_neg: 8

uncond_neg_samples: 0
uncond_neg_weight: 1.0

queue_size: 128

epochs: 2000
warmup_steps: 2000
temperatures: [0.02, 0.05, 0.2]
lr: 0.0002
weight_decay: 0.01
grad_clip: 2.0
ema_decay: 0.999
alpha_min: 1.0
alpha_max: 3.0
label_dropout: 0.1

mae:
  epochs: 1000
  lr: 0.001
  multi_scale: true
  weight_decay: 0.05
  finetune_classifier: true
  finetune_steps: 3000
  finetune_lr: 0.001

  mae_input_patch: 1
  mask_block_size: 2
  mask_prob: 0.5
  lambda_max: 0.1