name: mnist
model: DriftDiT-Tiny

use_feature_encoder: false
use_latent: false

img_size: 32 
in_channels: 1 # currently mnist does not support latent space training
num_classes: 10
samples_per_class: 8
batch_nc: 10
batch_n_pos: 32
batch_n_neg: 32

temperatures: [0.02, 0.05, 0.2]
lr: 0.0002
weight_decay: 0.01
grad_clip: 2.0
ema_decay: 0.999
warmup_steps: 1000
epochs: 1000
alpha_min: 1.0
alpha_max: 3.0
queue_size: 128
label_dropout: 0.1
