defaults:
  - dataset: cifar10
  - _self_

seed: 42
batch_size: 256
use_latent: ${dataset.use_latent}
latent_flip: true

num_workers: 4
log_step_interval: 10
save_interval: 10
sample_interval: 1

workspace_root: /home/ubt/1git/drifting_re
data_root: ${workspace_root}/data/
fid_dir: ${data_root}/${dataset.name}/fid
latent_dir: ${data_root}/${dataset.name}/latents

output_dir: /media/ubt/45d39189-c24c-4259-b12e-1d5d5e6071cc/outputs/

run_name: run_9_p2-${dataset.name}-${dataset.model}-L_${dataset.use_latent}-FE_${dataset.use_feature_encoder}-Img_${dataset.img_size}-BPos_${dataset.batch_n_pos}-UC_${dataset.uncond_neg_samples}
resume_from_ckpt: true
resume_dir: ${output_dir}/${dataset.name}/${run_name}/checkpoints
resume_ckpt: last.ckpt

mae_checkpoint_dir: ${output_dir}/${dataset.name}/${run_name}/mae_checkpoints/
resume_mae_ckpt: last.ckpt

# Feature encoder loading policy
ssl_checkpoint_path: null
allow_supervised_fallback: false

hydra:
  run:
    dir: ${output_dir}/${dataset.name}/${run_name}
  output_subdir: null
  job:
    chdir: true

logger:
  monitor: 'train_loss'