defaults:
  - config
  - _self_

checkpoint: ${resume_dir}/${resume_ckpt}
sample_output_dir: ${output_dir}/${dataset.name}/${run_name}/samples

samples:
  num_samples: 100
  samples_per_class: 10
  alpha: 1.5
  seed: 42
  compute_fid: true
  fid_num_samples: 1000
  fid_batch_size: 64
  fid_stats_path: ${fid_dir}/${dataset.name}_fid_stats.npz

num_workers: 4

hydra:
  run:
    dir: ${output_dir}/${dataset.name}/sample_log/${run_name}
  output_subdir: null
  job:
    chdir: true
